#!/usr/bin/env node
var merge = require('./'),
    fs = require('fs'),
    argv = require('minimist')(process.argv.slice(2));

if (argv.s || argv.stream) {
  merge(argv._, { stream: true })
} else {
  process.stdout.write(JSON.stringify(merge(argv._.map(function(n) {
      return JSON.parse(fs.readFileSync(n));
  })), null, 2));
}
